#!/bin/sh
# Rush-managed Git hook for commit message validation
# This hook is automatically installed by "rush install"

# Run commitlint to validate the commit message
npx --no -- commitlint --edit $1
